# Generated by Django 4.0.6 on 2022-07-07 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculationpu',
            name='fio',
        ),
        migrations.RemoveField(
            model_name='calculationpu',
            name='occupation',
        ),
        migrations.AlterField(
            model_name='salarytotal',
            name='month',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='CalculationEVA',
        ),
        migrations.DeleteModel(
            name='CalculationPU',
        ),
    ]
